import { getManifest, getChapter } from './services/bibleData'
import React,{useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{BookOpen,Library,StickyNote,Search,Moon,Sun,X,ChevronRight,Check,AlertTriangle,LoaderCircle,Languages,Send}from'lucide-react';
import{getManifest,getChapter}from'./services/bibleData';
import'./styles.css';
const N='parallel-notes-v6',T='parallel-theme-v6',LIMIT=2;
const k=x=>`${x.book}.${x.chapter}`;
function App(){
 const[m,setM]=useState(),[chapters,setChapters]=useState([]),[notes,setNotes]=useState(()=>{try{return JSON.parse(localStorage.getItem(N)||'{}')}catch{return{}}}),[picker,setPicker]=useState(false),[drawer,setDrawer]=useState(false),[sel,setSel]=useState('GEN'),[theme,setTheme]=useState(localStorage.getItem(T)||'light'),[err,setErr]=useState(''),[q,setQ]=useState(''),[saved,setSaved]=useState(true),[busy,setBusy]=useState(''),[mobileLang,setMobileLang]=useState('zh'),[compose,setCompose]=useState(null),[draft,setDraft]=useState('');
 const timer=useRef(),scroll=useRef(),loading=useRef(false),request=useRef(),anchor=useRef(),jump=useRef(),lastTop=useRef(0);
<<<<<<< HEAD
 useEffect(()=>{const c=new AbortController();(async()=>{try{const manifest=await getManifest(c.signal);const verses=await getChapter('GEN', 1, c.signal);setM(manifest);setChapters([{book:'GEN',chapter:1,verses}])}catch(e){if(e.name!=='AbortError')setErr(e.message)}})();return()=>c.abort()},[]);
=======
 useEffect(()=>{const c=new AbortController();(async()=>{try{const manifest=await getManifest(c.signal);const verses=await getChapter('GEN',1,c.signal);setM(manifest);setChapters([{book:'GEN',chapter:1,verses}])}catch(e){if(e.name!=='AbortError')setErr(e.message)}})();return()=>c.abort()},[]);
>>>>>>> origin/master
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem(T,theme)},[theme]);
 useEffect(()=>{setSaved(false);clearTimeout(timer.current);timer.current=setTimeout(()=>{localStorage.setItem(N,JSON.stringify(notes));setSaved(true)},250);return()=>clearTimeout(timer.current)},[notes]);
 const adjacent=useCallback((current,dir)=>{if(!m)return null;const i=m.books.findIndex(b=>b.code===current.book),book=m.books[i];if(dir>0){if(current.chapter<book.chapters)return{book:current.book,chapter:current.chapter+1};return m.books[i+1]?{book:m.books[i+1].code,chapter:1}:null}if(current.chapter>1)return{book:current.book,chapter:current.chapter-1};return m.books[i-1]?{book:m.books[i-1].code,chapter:m.books[i-1].chapters}:null},[m]);
 const capture=()=>{const host=scroll.current;if(!host)return null;const top=host.getBoundingClientRect().top;const node=[...host.querySelectorAll('[data-id]')].find(n=>n.getBoundingClientRect().bottom>top+6);return node?{id:node.dataset.id,offset:node.getBoundingClientRect().top-top}:null};
 useLayoutEffect(()=>{const a=anchor.current;if(!a||!scroll.current)return;const node=scroll.current.querySelector(`[data-id="${CSS.escape(a.id)}"]`);if(node){const top=scroll.current.getBoundingClientRect().top;scroll.current.scrollTop+=node.getBoundingClientRect().top-top-a.offset}anchor.current=null},[chapters]);
<<<<<<< HEAD
 const load=useCallback(async dir=>{if(loading.current||q||!chapters.length)return;const target=adjacent(dir>0?chapters.at(-1):chapters[0],dir);if(!target)return;loading.current=true;setBusy(dir>0?'down':'up');setErr('');request.current?.abort();request.current=new AbortController();try{const verses=await getChapter(target.book, target.chapter,request.current.signal);anchor.current=capture();setChapters(old=>dir>0?[...old,{...target,verses}].slice(-LIMIT):[{...target,verses},...old].slice(0,LIMIT))}catch(e){if(e.name!=='AbortError')setErr(e.message)}finally{loading.current=false;setBusy('')}},[chapters,adjacent,q]);
 useEffect(()=>{const el=scroll.current;if(!el)return;let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const now=el.scrollTop,down=now>=lastTop.current;lastTop.current=now;if(down&&el.scrollHeight-now-el.clientHeight<700)load(1);else if(!down&&now<360)load(-1)})};el.addEventListener('scroll',update,{passive:true});update();return()=>{cancelAnimationFrame(frame);el.removeEventListener('scroll',update)}},[load]);
 useEffect(()=>{const el=scroll.current;if(el&&chapters.length===1&&!loading.current&&el.scrollHeight<el.clientHeight+700)load(1)},[chapters,load]);
 const go=useCallback(async(book,chapter,verse=1)=>{request.current?.abort();loading.current=true;setBusy('jump');setErr('');try{const verses=await getChapter(book, chapter);jump.current=`${book}.${chapter}.${verse}`;setChapters([{book,chapter,verses}]);setPicker(false);setDrawer(false)}catch(e){setErr(e.message)}finally{loading.current=false;setBusy('')}},[]);
=======
 const load=useCallback(async dir=>{if(loading.current||q||!chapters.length)return;const target=adjacent(dir>0?chapters.at(-1):chapters[0],dir);if(!target)return;loading.current=true;setBusy(dir>0?'down':'up');setErr('');request.current?.abort();request.current=new AbortController();try{const verses=await getChapter(target.book,target.chapter,request.current.signal);anchor.current=capture();setChapters(old=>dir>0?[...old,{...target,verses}].slice(-LIMIT):[{...target,verses},...old].slice(0,LIMIT))}catch(e){if(e.name!=='AbortError')setErr(e.message)}finally{loading.current=false;setBusy('')}},[chapters,adjacent,q]);
 useEffect(()=>{const el=scroll.current;if(!el)return;let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const now=el.scrollTop,down=now>=lastTop.current;lastTop.current=now;if(down&&el.scrollHeight-now-el.clientHeight<700)load(1);else if(!down&&now<360)load(-1)})};el.addEventListener('scroll',update,{passive:true});update();return()=>{cancelAnimationFrame(frame);el.removeEventListener('scroll',update)}},[load]);
 useEffect(()=>{const el=scroll.current;if(el&&chapters.length===1&&!loading.current&&el.scrollHeight<el.clientHeight+700)load(1)},[chapters,load]);
 const go=useCallback(async(book,chapter,verse=1)=>{request.current?.abort();loading.current=true;setBusy('jump');setErr('');try{const verses=await getChapter(book,chapter);jump.current=`${book}.${chapter}.${verse}`;setChapters([{book,chapter,verses}]);setPicker(false);setDrawer(false)}catch(e){setErr(e.message)}finally{loading.current=false;setBusy('')}},[]);
>>>>>>> origin/master
 useLayoutEffect(()=>{if(!jump.current||!chapters.length)return;requestAnimationFrame(()=>{scroll.current?.querySelector(`[data-id="${CSS.escape(jump.current)}"]`)?.scrollIntoView({block:'center'});jump.current=null})},[chapters]);
 const flat=useMemo(()=>chapters.flatMap(c=>c.verses),[chapters]),shown=useMemo(()=>flat.filter(x=>!q||`${x.en} ${x.zh} ${notes[x.id]||''}`.toLowerCase().includes(q.toLowerCase())),[flat,q,notes]);
 const bookOrder=useMemo(()=>new Map((m?.books||[]).map((b,i)=>[b.code,i])),[m]);
 const items=useMemo(()=>Object.entries(notes).filter(([,text])=>String(text).trim()).map(([id,text])=>{const[book,ch,vs]=id.split('.'),meta=m?.books.find(x=>x.code===book);return{book,chapter:+ch,verse:+vs,title:`${meta?.name||book} ${ch}:${vs}`,zh:`${meta?.nameZh||''} ${ch}:${vs}`,text:String(text).trim()}}).sort((a,b)=>(bookOrder.get(a.book)??999)-(bookOrder.get(b.book)??999)||a.chapter-b.chapter||a.verse-b.verse),[notes,m,bookOrder]);
 const openComposer=x=>{if(!matchMedia('(max-width:850px)').matches)return;setCompose(x);setDraft(notes[x.id]||'')};
 const saveComposer=()=>{if(!compose)return;setNotes(current=>({...current,[compose.id]:draft}));setCompose(null)};
 return <main><header className="top"><div className="brand"><i><BookOpen/></i><b>Parallel Bible<small>ESV · 新譯本 · Notes</small></b></div><label className="search"><Search/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search / 搜尋"/></label><button className="nav"onClick={()=>setPicker(true)}><Library/>Books</button><button className="nav"onClick={()=>setDrawer(true)}><StickyNote/>Notes{items.length>0&&<em>{items.length}</em>}</button><button className="mobileLang"onClick={()=>setMobileLang(mobileLang==='zh'?'en':'zh')} aria-label="Switch Bible language"><Languages/><span>{mobileLang==='zh'?'繁中':'EN'}</span></button><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</button></header>{err&&<div className="error"><AlertTriangle/>{err}</div>}<section className={`reader mobile-${mobileLang}`}><div className="heads"><Head a="English" b="English Standard Version"/><Head a="繁體中文" b="中文新譯本"/><Head a="Notes" b="Free writing space">{saved&&<span><Check/>Saved</span>}</Head></div><div className="scroll"ref={scroll}>{busy==='up'&&<Loading/>}{chapters.map(section=><section className="chapterSection"key={k(section)}><div className="chapter">{section.verses[0]?.bookName} · {section.verses[0]?.bookNameZh}<strong>{section.chapter}</strong></div>{section.verses.filter(x=>shown.includes(x)).map(x=><div className={`row ${notes[x.id]?.trim()?'hasNote':''}`}key={x.id}data-id={x.id}onClick={()=>openComposer(x)}><Cell n={x.verse}kind="en">{x.en}</Cell><Cell n={x.verse}zh kind="zh">{x.zh}</Cell><div className="note"onClick={e=>e.stopPropagation()}><small>{x.chapter}:{x.verse}</small><textarea value={notes[x.id]||''}onChange={e=>setNotes({...notes,[x.id]:e.target.value})}placeholder="Write freely…"/></div><span className="mobileNoteDot"><StickyNote/></span></div>)}</section>)}{(busy==='down'||busy==='jump')&&<Loading/>}</div></section>{picker&&<Picker m={m}sel={sel}setSel={setSel}close={()=>setPicker(false)}go={go}/>} {drawer&&<Drawer items={items}close={()=>setDrawer(false)}go={go}/>} {compose&&<MobileComposer verse={compose} value={draft} setValue={setDraft} close={()=>setCompose(null)} save={saveComposer}/>}</main>}
function Loading(){return <div className="loading"><LoaderCircle/>Loading next chapter…</div>}function Head({a,b,children}){return <header><div><b>{a}</b><small>{b}</small></div>{children}</header>}function Cell({n,zh,kind,children}){return <div className={`cell ${kind||''}`}lang={zh?'zh-Hant':'en'}><b>{n}</b><p>{children}</p></div>}
function Picker({m,sel,setSel,close,go}){const book=m?.books.find(x=>x.code===sel)||m?.books[0];return <div className="shade"onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="picker"><ModalHead title="Books & Chapters"sub="書卷與章節快速導覽"close={close}/><div className="pickbody"><div className="books"><BookCol title="Old Testament · 舊約"books={m?.books.slice(0,39)||[]} {...{sel,setSel}}/><BookCol title="New Testament · 新約"books={m?.books.slice(39)||[]} {...{sel,setSel}}/></div><aside><span className="eyebrow">CHAPTER · 章</span><h2>{book?.nameZh}</h2><p>{book?.name}</p><div className="grid">{Array.from({length:book?.chapters||0},(_,i)=><button key={i+1}onClick={()=>go(book.code,i+1)}>{i+1}</button>)}</div></aside></div></section></div>}
function BookCol({title,books,sel,setSel}){return <div className="bookcol"><h3>{title}</h3>{books.map(x=><button key={x.code}className={sel===x.code?'active':''}onClick={()=>setSel(x.code)}><span>{x.nameZh}</span><small>{x.name}</small><ChevronRight/></button>)}</div>}
function Drawer({items,close,go}){let last='';return <div className="shade drawerShade"onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer"><ModalHead title="My Notes"sub={`${items.length} notes · 按書卷、章、節排序`}close={close}/><div className="list">{items.length?items.map(x=>{const group=`${x.book}.${x.chapter}`,heading=group!==last;last=group;return <React.Fragment key={`${group}.${x.verse}`}>{heading&&<div className="noteGroup">{x.title.split(':')[0]} · {x.zh.split(':')[0]}</div>}<button onClick={()=>go(x.book,x.chapter,x.verse)}><i><StickyNote/></i><span><b>{x.title}</b><small>{x.zh}</small><p>{x.text}</p></span><ChevronRight/></button></React.Fragment>}):<div className="empty"><StickyNote/><b>No notes yet</b><span>Your verse notes will appear here.</span></div>}</div></aside></div>}
function MobileComposer({verse,value,setValue,close,save}){const ref=useRef();useEffect(()=>{ref.current?.focus()},[]);return <div className="composerShade"onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="composer"role="dialog"aria-modal="true"aria-label={`Note for ${verse.ref}`}><div className="composerHandle"/><header><button onClick={close}aria-label="Cancel"><X/></button><div><small>{verse.bookNameZh} · {verse.chapter}:{verse.verse}</small><strong>{verse.zh}</strong></div><button className="saveNote"onClick={save}aria-label="Save note"><Send/></button></header><textarea ref={ref}value={value}onChange={e=>setValue(e.target.value)}placeholder="寫下筆記…"/><footer><span>筆記將連結至 {verse.bookNameZh} {verse.chapter}:{verse.verse}</span><button onClick={save}><Check/>完成</button></footer></section></div>}
function ModalHead({title,sub,close}){return <header className="modalhead"><div><b>{title}</b><small>{sub}</small></div><button onClick={close}><X/></button></header>}createRoot(document.getElementById('root')).render(<App/>);
